#!/usr/bin/env bash

APP="adapter"
AUTO_VERSION=commit-count+git-revision+branch-unless-master
TARGET_MIX_ENV=prod

BUILD_HOST="35.227.35.171"
BUILD_USER="sshilin"
BUILD_AT="/home/sshilin/build"

PRODUCTION_HOSTS="35.227.35.171"
PRODUCTION_USER="sshilin"
DELIVER_TO="/home/sshilin/releases/"

BRANCH=deploy

pre_erlang_get_and_update_deps() {
  # copy it from the local machine to the build host when building
  local _local_secret_config_file="./config/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    status "Copying '$_local_secret_config_file' file to build host"
    scp "$_local_secret_config_file" "$BUILD_USER@$BUILD_HOST:$BUILD_AT/config/prod.secret.exs"
  fi
}

post_erlang_get_and_update_deps() {
  if [ "$TARGET_MIX_ENV" = "$TARGET_MIX_ENV" ]; then
    status "create db"
    MIX_ENV="$TARGET_MIX_ENV" mix ecto.create

    status "start migration"
    MIX_ENV="$TARGET_MIX_ENV" mix ecto.migrate
  fi
}